services:
  mi-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mi-sql
    env_file:
      - ./.env
    ports:
      - "1433:1433"
    volumes:
      - mi-sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 1
    networks:
      - backend

  authservice:
    build:
      context: ./src/AuthService
      dockerfile: Dockerfile
    container_name: authservice
    depends_on:
      - mi-sql
    environment:
      - ConnectionStrings__AuthDb=Server=mi-sql,1433;Database=AuthServiceBD;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False
    ports:
      - "32780:8080"
    networks:
      - backend

  imagenservice:
    build:
      context: ./src/ImagenService
      dockerfile: Dockerfile
    container_name: imagenservice
    depends_on:
      - mi-sql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mi-sql,1433;Database=DigitalizacionImagenesBD;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False
    ports:
      - "32781:8080"
    networks:
      - backend

  gateway:
    build:
      context: ./src/Gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: on-failure
    depends_on:
      - authservice
      - imagenservice
    # Si necesitas variables de entorno extra:
    # env_file:
    #   - ./src/Gateway/.env
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./src/Gateway/ocelot.json:/app/ocelot.json:ro
      - ./src/Gateway/appsettings.json:/app/appsettings.json:ro
    ports:
      - "8081:8080"
    networks:
      - backend

volumes:
  mi-sql-data:

networks:
  backend:
    driver: bridge
