apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  # Application configuration
  APP_ENV: "development"
  LOG_LEVEL: "info"
  PORT: "8080"
  API_VERSION: "v1"
  CORS_ORIGINS: "*"
  MAX_CONNECTIONS: "100"
  TIMEOUT: "30"
  RATE_LIMIT: "1000"
  
  # Service discovery
  SERVICE_DISCOVERY_URL: "http://consul.microservices.svc.cluster.local:8500"
  
  # Cache configuration
  CACHE_TTL: "3600"
  CACHE_SIZE: "1000"
  
  # Queue configuration
  QUEUE_URL: "redis://redis.microservices.svc.cluster.local:6379"
  
  # Monitoring
  METRICS_PORT: "9090"
  HEALTH_CHECK_PATH: "/health"

