apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservicios-web-imagenes
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: authservice:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: SA_PASSWORD
            - name: ConnectionStrings__AuthDb
              value: >-
                Server=sqlserver:1433;
                Database=AuthServiceBD;
                User Id=sa;
                Password=$(SA_PASSWORD);
                TrustServerCertificate=True;
                Encrypt=False
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
