apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: microservicios-web-imagenes
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
