apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: microservicios-web-imagenes
spec:
  selector:
    app: sqlserver
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
