apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagen-service
  labels:
    app: imagen-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imagen-service
  template:
    metadata:
      labels:
        app: imagen-service
    spec:
      containers:
        - name: imagen-service
          image: imagen-service:latest
          imagePullPolicy: Never
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imagen-service-secret
                  key: SA_PASSWORD
            - name: ConnectionStrings__DefaultConnection
              value: >-
                Server=sqlserver:1433;
                Database=DigitalizacionImagenesBD;
                User Id=sa;
                Password=$(SA_PASSWORD);
                TrustServerCertificate=True;
                Encrypt=False
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
