apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: microservicios-web-imagenes
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
    
      root   /usr/share/nginx/html;
      index  index.html;
    
      # 1) CORS global
      add_header Access-Control-Allow-Origin  * always;
      add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
      add_header Access-Control-Allow-Headers "Authorization,Content-Type" always;
    
      # 2) Preflight OPTIONS: nada más devolvemos 204
      if ($request_method = OPTIONS) {
        return 204;
      }
    
      # 3) Proxy a /auth/* - usar el nombre del servicio de Kubernetes
      location /auth/ {
        proxy_pass         http://gateway-service.microservicios-web-imagenes.svc.cluster.local:8080/auth/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
      }
    
      location /api/ {
        proxy_pass         http://gateway-service.microservicios-web-imagenes.svc.cluster.local:8080/api/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
      }
    
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservicios-web-imagenes
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: miregistroacr1751945372.azurecr.io/frontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx-config

