apiVersion: v1
kind: Service
metadata:
  name: auth-service-nodeport
  labels:
    app: auth-service
    environment: dev
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: auth-service

