apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  labels:
    app: frontend
    environment: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
      protocol: TCP
      name: http
  selector:
    app: frontend

