apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
  labels:
    app: gateway
    environment: dev
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
      protocol: TCP
      name: http
  selector:
    app: gateway

