apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace donde despliegas todo el stack
namespace: microservicios-web-imagenes

# Lee cada directorio de base (deployments, services, secrets, configmaps…)
resources:
  - ../../base/auth-service
  - ../../base/imagen-service
  - ../../base/gateway
  - ../../base/frontend
  - ../../base/ingress
  - ../../base/sqlserver

# Aquí tus parches específicos de dev (versión de las imágenes, réplicas, env, etc.)
patches:
  - path: patch-resources.yaml
